SELECT * FROM MOVIES;

SELECT * FROM MOVIES WHERE GENRE = 'Sci-Fi';

SELECT * FROM MOVIES WHERE IMDB_SCORE >= 6.5;

SELECT * FROM MOVIES WHERE RIGHT(RATING, 1) = 'G' AND RUNTIME < 100;

SELECT AVG(RUNTIME), GENRE FROM MOVIES WHERE IMDB_SCORE < 7.5 GROUP BY GENRE;

UPDATE MOVIES SET RATING = 'R' WHERE TITLE = 'Starship Troopers';

SELECT CONCAT(ID, ' ',RATING) FROM MOVIES
WHERE GENRE = 'Horror' OR GENRE = 'Documentary';

SELECT RATING, AVG(IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE) FROM MOVIES GROUP BY RATING;

SELECT RATING, AVG(IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE) FROM MOVIES GROUP BY RATING HAVING COUNT(*) > 1;

DELETE FROM MOVIES WHERE RATING = 'R';